[project]
name = "repo-update-bot"
version = "1.0.0"
description = "Telegram Bot that sends every repo's release to your Telegram Channel."
dependencies = [
    "aiogram==3.21.0",
    "aiohttp==3.9.5",
    "python-dotenv==1.1.1"
]

[tool.setuptools.packages.find]
where = ["src"]
